language: haxe
dist: xenial
os:
  - mac
  - linux
  - windows

haxe:
  - stable
  - development

env:
  # Run basic tests for each combination of target language and operating system
  - KISS_TARGET=cpp
  - KISS_TARGET=interp
  - KISS_TARGET=js
  - KISS_TARGET=nodejs
  - KISS_TARGET=py
  # Test projects on every operating system
  - KISS_PROJECT=aoc
  - KISS_PROJECT=asciilib2
  - KISS_PROJECT=file-watch
  - KISS_PROJECT=kiss-vscode
  - KISS_PROJECT=nat-archive-tool
  - KISS_PROJECT=pdf-salad

jobs:
  # Allow Haxe development to fail.
  allow_failures:
    - haxe: development
  fast_finish: true
  include:
    # Check the formatting in a separate job so formatting failures don't hide more important ones
    - script: haxelib install formatter && haxelib run formatter --check -s .
      os: linux
      haxe: stable
    # TODO Check that every project is tested in this file

install:
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
      choco install nodejs-lts --version 12.13.1 -y; export PATH="/c/Program Files/nodejs:$PATH";
      choco install python --version 3.7.1 -y; export PATH="/c/Python37/Scripts:/c/Python37:$PATH";
    fi
  # Magic to make haxelib works https://github.com/HaxeFoundation/neko/issues/196
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
      curl -sSLf https://lib.haxe.org/p/jQueryExtern/3.2.1/download/ -o /dev/null;
    fi

script: ./test.sh
