<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string></string>
	<key>fileTypes</key>
	<array>
		<string>kiss</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\(</string>
	<key>foldingStopMarker</key>
	<string>\)</string>
	<key>keyEquivalent</key>
	<string>^~H</string>
	<key>name</key>
	<string>Kiss</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.kiss</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;|//).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.kiss</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function-type.kiss</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.kiss</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:\()((?i:defmacro|defMacro|defun|function|defmethod|method|def[A-Z]\S+))\s+((?:\w|[+\-<>/*&amp;=.?!$%:@\[\]^{}~#|])+)</string>
			<key>name</key>
			<string>meta.function.kiss</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?<=\s)(?i:&opt|&rest|&body)(?=\s+)</string>
			<key>name</key>
			<string>meta.function-parameters.kiss</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function-type.kiss</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.kiss</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:\()((?i:defvar|defprop|var|prop))\s+((?:\w|[+\-<>/*&amp;=.?!$%:@\[\]^{}~#|])+)</string>
		</dict>
		<!-- <dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.kiss</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#)(\w|[\\+-=&lt;&gt;'"&amp;#])+</string>
			<key>name</key>
			<string>constant.character.kiss</string>
		</dict> -->
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.kiss</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.kiss</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?<=^|\s|[()])(\*)(\S*)(\*)(?=$|\s|[()])</string>
			<key>name</key>
			<string>variable.other.global.kiss</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?<=^|\s|[()]):(\w|[+\-<>/*&amp;=.?!$%:@\[\]^{}~#|])*</string>
			<key>name</key>
			<string>keyword.constant.kiss</string>
		</dict>
		<dict>
			<key>match</key>
			<!-- TODO cut this down and add some missing ones -->
			<string>(?<=\()(?i:\*|\*\*|\*\*\*|\+|\+\+|\+\+\+|\-|/|//|///|/=|<|<=|=|>|>=|and|apply|assert|begin|break|case|catch|concat|cond|continue|count|defMacro|defReaderMacro|defun|defmethod|method|function|defvar|var|defprop|prop|for|doFor|eighth|eval|fifth|first|fourth|localFunction|localVar|symbol|if|load|withFunction|withFunctions|lambda|last|let|loop|map|max|min|ninth|not|nth|setNth|getDict|setDict|or|otherwise|print|rest|return|reverse|second|set|sixth|Some|sort|symbolName|symbolNameValue|tenth|the|third|throw|trace|when|unless|ifLet|whenLet|unlessLet|forCase|doForCase|with[A-Z]\S+)(?=\s+)</string>
			<key>name</key>
			<string>keyword.control.kiss</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?<=^|\s|[()])(?i:null|true|false)(?=$|\s|[()])</string>
			<key>name</key>
			<string>constant.language.kiss</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.kiss</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.kiss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.kiss</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.kiss</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.kiss</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(#+)"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.kiss</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"\1</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.kiss</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.kiss</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.kiss</string>
	<key>uuid</key>
	<string>00D451C9-6B1D-11D9-8DFA-000D93589AF6</string>
</dict>
</plist>
