name: CI

on: [push]

jobs:
  test-core:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        haxe-version: [4.2.2]
        node-version: ['14']
        python-version: ['3.x']
        test-target: 
          - KISS_TARGET=cpp
          - KISS_TARGET=cs
          - KISS_TARGET=interp
          - KISS_TARGET=js
          - KISS_TARGET=nodejs
          - KISS_TARGET=py
          - KISS_PROJECT=aoc
          - KISS_PROJECT=asciilib
          - KISS_PROJECT=flixel-ascii-game
          - KISS_PROJECT=flixel-rpg-tutorial
          - KISS_PROJECT=kiss-vscode
          - KISS_PROJECT=nat-archive-tool
          - KISS_PROJECT=nat-flixel-desktop-playground
          - KISS_PROJECT=habit-puzzle-game-flixel-desktop
          - KISS_PROJECT=pdf-salad
          - KISS_PROJECT=leet-code
          - KISS_PROJECT=sched
          - KISS_PROJECT=godot-squash-the-creeps-3d
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      CI_OS_NAME: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      # Set up Kiss runtimes:
      # haxe
      - uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: ${{ matrix.haxe-version }}
      # nodejs
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # python
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # mono
      - run: brew install mono || brew link --overwrite mono
        if: ${{ matrix.os == 'macos-latest' }}
      - run: choco install mono
        if: ${{ matrix.os == 'windows-latest' }}
      - run: |
          # instructions for ubuntu 20.04 from here: https://www.mono-project.com/download/stable/#download-lin
          sudo apt install gnupg ca-certificates
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt update
          sudo apt install mono-devel
        if: ${{ matrix.os == 'ubuntu-latest' }}
      # output debug info
      - run: haxe -version
      # run target test:
      - run: echo "${{ matrix.test-target }}" >> $GITHUB_ENV
      - run: ./test.sh
      
